#!/usr/bin/env python3
from os import name, system

def clear():
    if name == 'nt':
        system('cls')
    else:
        system('clear')

weaponDescriptions = {
        'Plasma Rifle': '',
        'AK-47': '',
        'Dual Vipers': '',
        'Pipe Rifle': '',
        'Carbon Rifle': '',
        'Carbon Pistol': '',
        'Thunder Gun': '',
        'Blight Rifle': '',
        'Chaos Blade': 'Crackling with harsh crimson energy, this rifle hums with chaos itself. Once pulled, keep this weapon until the end of combat, instead of it vanishing after the first use.',
        'Chaos Cannon': '',
        'Thermos': '',
        'Candy Corn': '',
        'Chip Bag': '',
        'Fist Full of Grass': '',
        'Kazoo': '',
        'Rainbow Blaster': '',
        'Billy Club': '',
        'Sniper Rifle': '',
        'Sub Sandwich': '',
        'Hot Dog': '',
        'Cheeto': '',
        'Chemistry Textbook': '',
        'Skull': '',
        'Dentures': '',
        'A Slimy Fish': '',
        'Keyboard': '',
        'Lighter': '',
        'Candle': '',
        'Radio': '',
        'Car': '',
        'Minigun': '',
        'Camera': '',
        'Wooden Rod': '',
        'Leaf': '',
        'Trashcan': '',
        'Poison Ivy': '',
        'Vacuum': '',
        'Photon Blaster': '',
        'Shielded Anti-matter Blade': '',
        'Grav Cannon': '',
        'Cup of Acid': '',
        'Toothpick': '',
        'Spatula': '',
        'Spork': '',
        'Fpoon': '',
        'Angry Cat': '',
        'Fire Extinguisher': '',
        'Grappling Hook': '',
        'Brick': '',
        'Pickaxe': '',
        'Auto Rifle': '',
        'Repeating Rifle': '',
        'Blitz Rifle': '',
        'Charge Rifle': '',
        'Hand Cannon': '',
        'Sidearm': '',
        'Railgun': '',
        'Split Rifle': '',
        'Cutlass': '',
        'Dagger': '',
        'Longsword': '',
        'Shortsword': '',
        'Glaive': '',
        'Trident': '',
        'Rusty Copper Sword': '',
        'Whip': '',
        'Brass Knuckles': '',
        'Cutlass': '',
        'Severed Leg': '',
        'Hand missing three fingers': '',
        'Potato gun': '',
        'Jeff': '',
        'Tree': '',
        'A tiny tuna': '',
        'A large tuna': '',
        'A sword fish attached to a sword hilt': '',
        'A bowl of oatmeal': '',
        'Blurred middle finger': '',
        'Bag of Dice': '',
        'Dice Tray': '',
        'Loads of D6s': '',
        'Random playing cards': '',
        'Scythe': '',
        'Pool Noodle': '',
        'T800 skull': '',
        'Low poly traffic cone': '',
        'Rainbow bridge': '',
        'Taco': '',
        'A pillow filled with glass': '',
        'A "normal" pillow': '',
        'TV': '',
        'Entertainment system': '',
        'CD Rom': '',
        'Rumba': '',
        'Empty soup can': '',
        'Full soup can': '',
        'Suitcase': '',
        'Backpack full of rocks': '',
        'The Book of all knowledge': '',
        'Computer Monitor': '',
        'Pocket Knife': '',
        'Shank': '',
        'Signature cooking knives': '',
        'Poison Dart': '',
        'Liquid Sword': '',
        'Slingshot that shoots Peas': '',
        'Cellphone': '',
        'Lightsaber': '',
        'Cloud of knives': '',
        'Shark sword': '',
        'W.M.D.': '',
        'Frying Pan': '',
        'Phaser': '',
        'Han Solo\'s Blaster': '',
        'FN P90': '',
        'Fist full of spicy ramen': '',
        'Fist full of fists': '',
        'Sonic Rifle': '',
        'Quarterstaff': '',
        'Halfstaff': '',
        '3/4thsStaff': '',
        'Ballpoint Pen': '',
        'The Stick': '',
        'Nail Gun': '',
        'Crow ring': '',
        'Mining Laser': '',
        'Lawn Darts': '',
        'Sword of Athena': '',
        'Hammer of Hephaestus': '',
        'Can of Spam': '',
        'Vorpal Sword': '',
        'Ninja Star': '',
        'Katana': '',
        'Fan Blades': 'Katana Wins!',
        'Drothum\'s Scythe': '',
        'Basket': '',
        'Red hot tongs': '',
        'Baseball': '',
        'Completely average Baseball (filled with glass)': '',
        'Supersoaker': '',
        'Computer mouse': '',
        'Knight\'s helmet': '',
        'Very angry mouse': '',
        'Blade of Ice': '',
        'Blade of Fire': '',
        'Subwoofer': 'wubwubwub',
        'Grenade': 'Kill someone on impact, then it explodes.',
        'Piranha Plant': 'chomp chomp',
        'Full Body Waifu Pillow': 'So many choices, yet only one is right. Debate.',
        'Jane': 'She screams into your mind, or wishes she could...',
        'A beating heart': 'Still bleeding, who did you just pull this from?!',
        'The Killer Rabbit of Caerbannog': 'We better not risk another frontal assault, that rabbit\'s dynamite.',
        'Spam Gun': 'EAT this! Actually, eat it.',
        'Eroshevaal\'s Ether Bow': 'This seems pretty meta...',
        'Dog Meat': 'The dog',
        'Dog meat': 'Actually just meat of a dog',
        'The Chaos Gauntlet': 'Wait, this isn\'t right...',
        'Mallet': 'Bonk',
        'Rubber Mallet': 'Soft Bonk',
        'Flaming Baseball': '',
        'Frozen Baseball': '',
        'Broken Beer Bottle': 'Get\'r another, will yuh?',
        'Fullstaff': 'Like a quarterstaff, but 4 of them.',
        'Sanic Rifle': 'Gotta go fast',
        'Ion Saber': 'That\'s not how any of this should work!',
        'Storm Trooper Helmet': 'Good luck hitting anything with this.',
        'Sarcastic Goldfish': 'He\'s SO glad you threw him at your worst enemy.',
        'The Demon Core': 'Dude that\'s rad.',
        'Bag of soggy pickles': 'The worst part is the noise.',
        'Cat litter': 'Meow?',
        'Bottle of Bleach': 'Perfect for the eyes!',
        'Zeus\' Lightning Bolt': 'CRAAAACKOOOBOOOOM',
        'Blade of Ice and Fire': 'Thank you George R. R. Martin',
        'Toaster': 'Fire bread like bullets! D20 roll to see how crispy the bread is.',
        'Lego': '',
        'Half Empty Bag of Flour': 'Pessimism can kill!',
        'Half Full Bag of Flour': 'Optimism can kill!',
        'Fire Flower': 'YE HEI!',
        'Alligator Snapping Turtle': '',
        'David\'s right eyeball': 'Who\'s David? We don\'t know!',
        'Mjölnir': 'You are not worthy! It drops to the ground until the next turn. Who says you can\'t hit *it* with *people*?',
        'A block of Stinky Bishop cheese': 'ew',
        'The black knight from monty python': 'Becomes an ally during the fight, every time he takes damage, he loses a body part, until he loses all of his limbs. "It\'s just a flesh wound!"',
        'Pixar lamp': 'Smush, smush, smush, smush, look around, fade to black.',
}
