#!/usr/bin/env python3
from os import name, system

def clear():
    if name == 'nt':
        system('cls')
    else:
        system('clear')

weapons = [
        'Plasma Rifle',
        'AK-47',
        'Dual Vipers',
        'Pipe Rifle',
        'Carbon Rifle',
        'Carbon Pistol',
        'Thunder Gun',
        'Blight Rifle',
        'Chaos Blade',
        'Chaos Cannon',
        'Thermos',
        'Candy Corn',
        'Chip Bag',
        'Fist Full of Grass',
        'Kazoo',
        'Rainbow Blaster',
        'Billy Club',
        'Sniper Rifle',
        'Sub Sandwich',
        'Hot Dog',
        'Cheeto',
        'Chemistry Textbook',
        'Skull',
        'Dentures',
        'A Slimy Fish',
        'Keyboard',
        'Lighter',
        'Candle',
        'Radio',
        'Car',
        'Minigun',
        'Camera',
        'Wooden Rod',
        'Leaf',
        'Trashcan',
        'Poison Ivy',
        'Vacuum',
        'Photon Blaster',
        'Shielded Anti-matter Blade',
        'Grav Cannon',
        'Cup of Acid',
        'Toothpick',
        'Spatula',
        'Spork',
        'Fpoon',
        'Angry Cat',
        'Fire Extinguisher',
        'Grappling Hook',
        'Brick',
        'Pickaxe',
        'Auto Rifle',
        'Repeating Rifle',
        'Blitz Rifle',
        'Charge Rifle',
        'Hand Cannon',
        'Sidearm',
        'Railgun',
        'Split Rifle',
        'Cutlass',
        'Dagger',
        'Longsword',
        'Shortsword',
        'Glaive',
        'Trident',
        'Rusty Copper Sword',
        'Whip',
        'Brass Knuckles',
        'Cutlass',
        'Severed Leg',
        'Hand missing three fingers',
        'Potato gun',
        'Jeff',
        'Tree',
        'A tiny tuna',
        'A large tuna',
        'A sword fish attached to a sword hilt',
        'A bowl of oatmeal',
        'Blurred middle finger',
        'Bag of Dice',
        'Dice Tray',
        'Loads of D6s',
        'Random playing cards',
        'Scythe',
        'Pool Noodle',
        'T800 skull',
        'Low poly traffic cone',
        'Rainbow bridge',
        'Taco',
        'A pillow filled with glass',
        'A "normal" pillow',
        'TV',
        'Entertainment system',
        'CD Rom',
        'Rumba',
        'Empty soup can',
        'Full soup can',
        'Suitcase',
        'Backpack full of rocks',
        'The Book of all knowledge',
        'Computer Monitor',
        'Pocket Knife',
        'Shank',
        'Signature cooking knives',
        'Poison Dart',
        'Liquid Sword',
        'Slingshot that shoots Peas',
        'Cellphone',
        'Lightsaber',
        'Cloud of knives',
        'Shark sword',
        'W.M.D.',
        'Frying Pan',
        'Phaser',
        'Han Solo\'s Blaster',
        'FN P90',
        'Fist full of spicy ramen',
        'Fist full of fists',
        'Sonic Rifle',
        'Quarterstaff',
        'Halfstaff',
        '3/4thsStaff',
        'Ballpoint Pen',
        'The Stick',
        'Nail Gun',
        'Crow ring',
        'Mining Laser',
        'Lawn Darts',
        'Sword of Athena',
        'Hammer of Hephaestus',
        'Can of Spam',
        'Vorpal Sword',
        'Ninja Star',
        'Katana',
        'Fan Blades',
        'Drothum\'s Scythe',
        'Basket',
        'Red hot tongs',
        'Baseball',
        'Completely average Baseball (filled with glass)',
        'Supersoaker',
        'Computer mouse',
        'Knight\'s helmet',
        'Very angry mouse',
        'Blade of Ice',
        'Blade of Fire',
        'Subwoofer',
        'Grenade',
        'Piranha Plant',
        'Full Body Waifu Pillow',
        'Jane',
        'A beating heart',
        'The Killer Rabbit of Caerbannog',
        'Spam Gun',
        'Eroshevaal\'s Ether Bow',
        'Dog Meat',
        'Dog meat',
        'The Chaos Gauntlet',
        'Mallet',
        'Rubber Mallet',
        'Flaming Baseball',
        'Frozen Baseball',
        'Broken Beer Bottle',
        'Fullstaff',
        'Sanic Rifle',
        'Ion Saber',
        'Storm Trooper Helmet',
        'Sarcastic Goldfish',
        'The Demon Core',
        'Bag of soggy pickles',
        'Cat litter',
        'Bottle of Bleach',
        'Zeus\' Lightning Bolt',
        'Blade of Ice and Fire',
        'Toaster',
        'Lego',
        'Half Empty Bag of Flour',
        'Half Full Bag of Flour',
        'Fire Flower',
        'Alligator Snapping Turtle',
        'David\'s right eyeball',
        'Mjölnir',
        'A block of Stinky Bishop cheese',
        'The black knight from monty python',
        'Pixar lamp',
]
